import { useState, useEffect } from "react";
import { approveWikiPage, rejectWikiPage, getProposedContent, ReviewPage } from "../../lib/tauri";

interface Props {
  queue: ReviewPage[];
  vaultPath: string;
  onClose: () => void;
  onAction: () => void;
}

export function ReviewModal({ queue, vaultPath, onClose, onAction }: Props) {
  const [idx, setIdx] = useState(0);
  const [busy, setBusy] = useState(false);
  const [content, setContent] = useState<string | null>(null);

  const page = queue[Math.min(idx, queue.length - 1)];

  useEffect(() => {
    setContent(null);
    if (!page) return;
    getProposedContent(page.id).then(setContent).catch(() => setContent(null));
  }, [page?.id]);

  if (queue.length === 0) {
    return (
      <div className="review-overlay" onClick={onClose}>
        <div className="review-modal" onClick={(e) => e.stopPropagation()}>
          <h2>Review Queue</h2>
          <p className="placeholder">No pages pending review.</p>
          <button className="review-btn review-btn--secondary" onClick={onClose}>Close</button>
        </div>
      </div>
    );
  }

  async function handleApprove() {
    if (!page) return;
    setBusy(true);
    try {
      const approveContent = content ?? `# ${page.path}\n\n*Generated by ${page.generated_by}*`;
      await approveWikiPage(page.id, approveContent, vaultPath);
      onAction();
      if (idx >= queue.length - 1) setIdx(Math.max(0, queue.length - 2));
    } finally {
      setBusy(false);
    }
  }

  async function handleReject() {
    if (!page) return;
    setBusy(true);
    try {
      await rejectWikiPage(page.id);
      onAction();
      if (idx >= queue.length - 1) setIdx(Math.max(0, queue.length - 2));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="review-overlay" onClick={onClose}>
      <div className="review-modal review-modal--wide" onClick={(e) => e.stopPropagation()}>
        <div className="review-header">
          <h2>Review Queue ({queue.length})</h2>
          <button className="review-close" onClick={onClose}>✕</button>
        </div>
        <div className="review-meta">
          <strong>{page.path}</strong>
          <span className="review-model">Generated by {page.generated_by}</span>
        </div>
        <p className="review-hint">
          Sources: {JSON.parse(page.source_doc_ids || "[]").join(", ")}
        </p>
        {content !== null ? (
          <pre className="review-content">{content}</pre>
        ) : (
          <p className="review-hint">Loading proposed content…</p>
        )}
        <div className="review-nav">
          <button disabled={idx === 0} onClick={() => setIdx(idx - 1)}>← Prev</button>
          <span>{idx + 1} / {queue.length}</span>
          <button disabled={idx >= queue.length - 1} onClick={() => setIdx(idx + 1)}>Next →</button>
        </div>
        <div className="review-actions">
          <button className="review-btn review-btn--approve" onClick={handleApprove} disabled={busy}>
            ✓ Approve &amp; save to wiki
          </button>
          <button className="review-btn review-btn--reject" onClick={handleReject} disabled={busy}>
            ✗ Reject
          </button>
        </div>
      </div>
    </div>
  );
}
