import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  approveWikiPage,
  rejectWikiPage,
  getProposedContent,
  ReviewPage,
} from "../../lib/tauri";
import { useIndexingStatus } from "../../hooks/useIndexingStatus";
import { useReviewKeyboard } from "../../hooks/useReviewKeyboard";
import {
  adjacentQueueId,
  nextQueueSelectionId,
  sortReviewQueue,
} from "../../lib/reviewQueue";
import { saveRejectReason } from "../../lib/reviewRejectReasons";
import { ReviewQueueList } from "../review/ReviewQueueList";
import { ReviewEvidencePanel } from "../review/ReviewEvidencePanel";
import { ReviewProposalEditor } from "../review/ReviewProposalEditor";

interface Props {
  queue: ReviewPage[];
  onAction: () => void;
  vaultPath: string;
}

export function ReviewMode({ queue, onAction, vaultPath }: Props) {
  const [selectedId, setSelectedId] = useState<ReviewPage["id"] | null>(null);
  const [checkedIds, setCheckedIds] = useState<Set<number>>(() => new Set());
  const [busy, setBusy] = useState(false);
  const [proposedContent, setProposedContent] = useState<string | null>(null);
  const [editedContent, setEditedContent] = useState("");
  const editorRef = useRef<HTMLDivElement>(null);
  const { indexed } = useIndexingStatus(vaultPath);

  const sortedQueue = useMemo(() => sortReviewQueue(queue), [queue]);
  const page =
    sortedQueue.find((p) => p.id === selectedId) ?? sortedQueue[0] ?? null;

  useEffect(() => {
    setCheckedIds((prev) => {
      const next = new Set<number>();
      for (const id of prev) {
        if (queue.some((p) => p.id === id)) next.add(id);
      }
      return next;
    });
  }, [queue]);

  useEffect(() => {
    setProposedContent(null);
    setEditedContent("");
    if (!page) return;
    getProposedContent(page.id)
      .then(setProposedContent)
      .catch(() => setProposedContent(null));
  }, [page?.id]);

  const handleEditedContentChange = useCallback((content: string) => {
    setEditedContent(content);
  }, []);

  const handleToggleChecked = useCallback((id: number, checked: boolean) => {
    setCheckedIds((prev) => {
      const next = new Set(prev);
      if (checked) next.add(id);
      else next.delete(id);
      return next;
    });
  }, []);

  const handleSelectNext = useCallback(() => {
    if (!page) return;
    const nextId = adjacentQueueId(sortedQueue, page.id, "next");
    if (nextId !== null) setSelectedId(nextId);
  }, [page, sortedQueue]);

  const handleSelectPrev = useCallback(() => {
    if (!page) return;
    const prevId = adjacentQueueId(sortedQueue, page.id, "prev");
    if (prevId !== null) setSelectedId(prevId);
  }, [page, sortedQueue]);

  const handleFocusEditor = useCallback(() => {
    editorRef.current?.focus();
  }, []);

  const handleApprove = useCallback(async () => {
    if (!page || busy) return;
    setBusy(true);
    try {
      const approveContent =
        proposedContent ?? `# ${page.path}\n\n*Generated by ${page.generated_by}*`;
      await approveWikiPage(page.id, approveContent);
      const nextId = nextQueueSelectionId(sortedQueue, page.id);
      setSelectedId(nextId);
      setCheckedIds((prev) => {
        const next = new Set(prev);
        next.delete(page.id);
        return next;
      });
      onAction();
    } finally {
      setBusy(false);
    }
  }, [
    page,
    busy,
    editedContent,
    proposedContent,
    sortedQueue,
    onAction,
  ]);

  const handleReject = useCallback(async () => {
    if (!page || busy) return;

    const reason = window.prompt("Reject reason (optional):");
    if (reason === null) return;

    setBusy(true);
    try {
      if (reason.trim()) saveRejectReason(page.id, reason.trim());
      await rejectWikiPage(page.id);
      const nextId = nextQueueSelectionId(sortedQueue, page.id);
      setSelectedId(nextId);
      setCheckedIds((prev) => {
        const next = new Set(prev);
        next.delete(page.id);
        return next;
      });
      onAction();
    } finally {
      setBusy(false);
    }
  }, [page, busy, sortedQueue, onAction]);

  const handleBatchApprove = useCallback(async () => {
    if (checkedIds.size === 0 || busy) return;
    setBusy(true);
    try {
      const ids = sortReviewQueue(
        sortedQueue.filter((p) => checkedIds.has(p.id)),
      ).map((p) => p.id);

      for (const id of ids) {
        const item = sortedQueue.find((p) => p.id === id);
        if (!item) continue;
        const content =
          item.id === page?.id && editedContent
            ? editedContent
            : await getProposedContent(id);
        await approveWikiPage(id, content);
      }

      setCheckedIds(new Set());
      if (page && checkedIds.has(page.id)) {
        setSelectedId(nextQueueSelectionId(sortedQueue, page.id));
      }
      onAction();
    } finally {
      setBusy(false);
    }
  }, [checkedIds, busy, sortedQueue, page, editedContent, onAction]);

  useReviewKeyboard({
    enabled: queue.length > 0 && !busy,
    onApprove: () => void handleApprove(),
    onReject: () => void handleReject(),
    onNext: handleSelectNext,
    onPrev: handleSelectPrev,
    onFocusEditor: handleFocusEditor,
  });

  if (queue.length === 0) {
    return (
      <div className="mode-layout review-screen">
        <div className="review-empty">
          <h2>Queue clear</h2>
          <p className="placeholder">
            Librarian watching {indexed} document{indexed === 1 ? "" : "s"}.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="mode-layout review-screen review-desk">
      <ReviewQueueList
        queue={queue}
        selectedId={page?.id ?? null}
        checkedIds={checkedIds}
        onSelect={setSelectedId}
        onToggleChecked={handleToggleChecked}
        onBatchApprove={() => void handleBatchApprove()}
        batchBusy={busy}
      />
      <main className="review-detail">
        {page && (
          <>
            <div className="review-meta">
              <strong>{page.path}</strong>
              <span className="review-model">
                Generated by {page.generated_by}
              </span>
            </div>
            <ReviewProposalEditor
              page={page}
              proposedContent={proposedContent}
              onEditedContentChange={handleEditedContentChange}
              containerRef={editorRef}
            />
            <div className="review-actions">
              <button
                className="review-btn review-btn--approve"
                onClick={() => void handleApprove()}
                disabled={busy}
              >
                ✓ Approve &amp; save to wiki
              </button>
              <button
                className="review-btn review-btn--reject"
                onClick={() => void handleReject()}
                disabled={busy}
              >
                ✗ Reject
              </button>
              <span className="review-shortcuts-hint">
                a approve · r reject · e edit · j/k navigate · space next
              </span>
            </div>
          </>
        )}
      </main>
      {page && (
        <ReviewEvidencePanel
          page={page}
          onSourceClick={() => {
            /* Library navigation deferred until cross-mode routing exists */
          }}
        />
      )}
    </div>
  );
}
