import { useEffect, useState } from "react";
import {
  approveWikiPage,
  rejectWikiPage,
  getProposedContent,
  ReviewPage,
} from "../../lib/tauri";

interface Props {
  queue: ReviewPage[];
  onAction: () => void;
}

export function ReviewMode({ queue, onAction }: Props) {
  const [selectedId, setSelectedId] = useState<ReviewPage["id"] | null>(null);
  const [busy, setBusy] = useState(false);
  const [content, setContent] = useState<string | null>(null);

  const page = queue.find((p) => p.id === selectedId) ?? queue[0] ?? null;

  useEffect(() => {
    setContent(null);
    if (!page) return;
    getProposedContent(page.id).then(setContent).catch(() => setContent(null));
  }, [page?.id]);

  if (queue.length === 0) {
    return (
      <div className="mode-layout review-screen">
        <div className="review-empty">
          <h2>Queue clear</h2>
          <p className="placeholder">
            The librarian is watching your documents. New proposals will
            appear here.
          </p>
        </div>
      </div>
    );
  }

  async function handleApprove() {
    if (!page) return;
    setBusy(true);
    try {
      const approveContent =
        content ?? `# ${page.path}\n\n*Generated by ${page.generated_by}*`;
      await approveWikiPage(page.id, approveContent);
      setSelectedId(null); // fall back to the queue head after refresh
      onAction();
    } finally {
      setBusy(false);
    }
  }

  async function handleReject() {
    if (!page) return;
    setBusy(true);
    try {
      await rejectWikiPage(page.id);
      setSelectedId(null);
      onAction();
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mode-layout review-screen">
      <aside className="sidebar review-queue-list">
        <h3 className="review-queue-heading">Review Queue ({queue.length})</h3>
        {queue.map((p) => (
          <button
            key={p.id}
            className={`review-queue-item${
              page?.id === p.id ? " review-queue-item--active" : ""
            }`}
            onClick={() => setSelectedId(p.id)}
          >
            <span className="review-queue-item-path">{p.path}</span>
            <span className="review-queue-item-model">{p.generated_by}</span>
          </button>
        ))}
      </aside>
      <main className="review-detail">
        {page && (
          <>
            <div className="review-meta">
              <strong>{page.path}</strong>
              <span className="review-model">
                Generated by {page.generated_by}
              </span>
            </div>
            <p className="review-hint">
              Sources: {JSON.parse(page.source_doc_ids || "[]").join(", ")}
            </p>
            {content !== null ? (
              <pre className="review-content">{content}</pre>
            ) : (
              <p className="review-hint">Loading proposed content…</p>
            )}
            <div className="review-actions">
              <button
                className="review-btn review-btn--approve"
                onClick={handleApprove}
                disabled={busy}
              >
                ✓ Approve &amp; save to wiki
              </button>
              <button
                className="review-btn review-btn--reject"
                onClick={handleReject}
                disabled={busy}
              >
                ✗ Reject
              </button>
            </div>
          </>
        )}
      </main>
    </div>
  );
}
