import { useEffect, useRef } from "react";
import type { EntityFact } from "../../lib/tauri";

interface Props {
  fact: EntityFact;
  open: boolean;
  onClose: () => void;
}

export function FactPowerMenu({ fact, open, onClose }: Props) {
  const dialogRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    dialogRef.current?.focus();
    function handleKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [open, onClose]);

  if (!open) return null;
  const hasProvenance =
    fact.okf_sources.length > 0 ||
    fact.okf_verified.length > 0 ||
    fact.okf_usage_window != null;
  return (
    <div
      ref={dialogRef}
      className="fact-power-menu"
      role="dialog"
      aria-label="Fact details"
      tabIndex={-1}
    >
      <header className="fact-power-menu-header">
        <h3>Fact details</h3>
        <button type="button" onClick={onClose} aria-label="Close">
          ×
        </button>
      </header>
      <dl className="fact-power-menu-grid">
        <dt>Raw id</dt>
        <dd>
          <code>{fact.id}</code>
        </dd>
        <dt>Lifecycle</dt>
        <dd>{fact.lifecycle_status}</dd>
        <dt>Stale after</dt>
        <dd>
          {fact.stale_after
            ? new Date(fact.stale_after).toISOString().slice(0, 10)
            : "—"}
        </dd>
        <dt>Generated by</dt>
        <dd>{fact.generated_by ?? "—"}</dd>
      </dl>
      {hasProvenance ? (
        <>
          <section>
            <h4>Sources</h4>
            {fact.okf_sources.length === 0 ? (
              <p className="placeholder">No sources recorded.</p>
            ) : (
              <ul>
                {fact.okf_sources.map((s, i) => (
                  <li key={i}>
                    <code>{s.resource}</code>
                    {s.title && <span> — {s.title}</span>}
                    {s.author && <span> (by {s.author})</span>}
                    {s.usage_count != null && (
                      <span> · used {s.usage_count}×</span>
                    )}
                    {s.last_modified && (
                      <span> · modified {s.last_modified}</span>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </section>
          <section>
            <h4>Verified by</h4>
            {fact.okf_verified.length === 0 ? (
              <p className="placeholder">No verifications recorded.</p>
            ) : (
              <ul>
                {fact.okf_verified.map((v, i) => (
                  <li key={i}>
                    <code>{v.by}</code> at {new Date(v.at).toISOString()}
                  </li>
                ))}
              </ul>
            )}
          </section>
          {fact.okf_usage_window && (
            <section>
              <h4>Usage window</h4>
              <p>
                {fact.okf_usage_window.from} → {fact.okf_usage_window.to}
              </p>
            </section>
          )}
        </>
      ) : (
        <p className="placeholder">
          No provenance recorded for this fact. Imported bundles carry v0.2
          sources; librarian-committed facts do not yet.
        </p>
      )}
    </div>
  );
}